### ISSUE TITLE
Need help regarding source code

### ISSUE THREAD

**Issue by Raulrj13** [pawitp/muwifi-autologin#1]
With due respect i would like to seek permission to use your source code of MU login  and monetize with it if you have no objections. To introduce myself, I'm a 17y enthusiast from India. If any objections I shall surely drop the idea and respect your concern. Thanking you.

**Comment by pawitp** [comment]
Please see the license at https://github.com/pawitp/muwifi-autologin/blob/master/LICENSE.txt.

All source code is licensed under the simplified BSD license and you may use it as long as attribution is given correctly. (But if you plan to monetize the application as a whole, rather than using a part of the source code to build your own application, then I will strongly advise against it. There's no market for it anyway.)

The application's logo belongs to Mahidol University and may NOT be used.

**Comment by Raulrj13** [comment]
I wish to integrate a part of source code and my app will be used for
different purpose. Also I would happy to receive your help as I'm quite new
with this. Thanking you.

**Comment by pawitp** [comment]
You may use the source code as you wish, however, I will not provide any help regarding the code because I don't have the time to do so.

**Comment by Raulrj13** [comment]
Thanks a lot sir. It was very generous of you to give your time to me.
